### PR TITLE
removes logging package

### PR DESCRIPTION
**Pull request by ppapapetrou76**
We have migrated all internal tooling projects to use the logging package 
of `internal-cloud-sdk-go` so it's safe to remove this package completely 

## Related Issues
https://github.com/elastic/cloud-deployer/pull/562
https://github.com/elastic/soteria/pull/1036

## Motivation and Context
One less package to worry

### CODE REVIEW

**Review by karencfv — COMMENTED** [review]
Thanks @ppapapetrou76 🙇‍♀️ Although, I'm not sure we can remove packages at this point since we're out of beta and we don't plan on releasing another major version any time soon. I doubt anyone outside of the Cloud team is using this package but still 🤔 

What do you think @Kushmaro ?

**Comment by Kushmaro** [comment]
@karencfv could you elaborate exactly what does this affect? Not sure I get that from this ticket

**Comment by karencfv** [comment]
Sure thing @Kushmaro . Basically, there is a `logging` package which can be used by anyone importing our SDK. It is very unlikely that anyone outside of the Cloud team is using this package, but we can't know for sure. If we were to remove this package it would be a pretty big breaking change.

For us it's best to remove this package, but again we can't be sure anyone outside is using it or not.

**Comment by marclop** [comment]
I generally agree with this, but it doesn't seem like anyone is importing this package or any of the sub-packages:

* [logging](https://pkg.go.dev/github.com/elastic/cloud-sdk-go@v1.2.0/pkg/logging?tab=importedby)
* [logging/decorator](https://pkg.go.dev/github.com/elastic/cloud-sdk-go@v1.2.0/pkg/logging/decorator?tab=importedby)
* [logging/logger/standardoutput](https://pkg.go.dev/github.com/elastic/cloud-sdk-go@v1.2.0/pkg/logging/logger/standardoutput?tab=importedby)
* [logging/logger/elasticsearch](https://pkg.go.dev/github.com/elastic/cloud-sdk-go@v1.2.0/pkg/logging/logger/elasticsearch?tab=importedby)

We could easily remove the package in `1.3.0` and mark it as a "breaking" change. If anyone is using this package, they won't be able to upgrade to `1.3.0` and we'll most likely hear from them.

**Comment by Kushmaro** [comment]
I'm ok with marking this explicitly as breaking, and waiting for external feedback if such exists @marclop @karencfv

**Comment by karencfv** [comment]
Sounds good to me! We should wait to merge this PR once we know for sure there won't be a 2.8.2 ECE release

**Comment by ppapapetrou76** [comment]
> Sounds good to me! We should wait to merge this PR once we know for sure there won't be a 2.8.2 ECE release

@karencfv hmmm why? Can't we / Aren't we supposed to release patch versions from the `2.8` tag? and not from master?

**Pull request merged**
