### PR TITLE
apivalidation: Set workflow to Go 1.14

### PR DESCRIPTION
**Pull request by karencfv**
## Description
This PR attempts to fix the broken validation tests. This same workflow 
works fine on an internal project using go 1.13, let's try 1.14 and see if it
works.

Additionally I have removed a couple of env vars from the workflow as
they are not needed.

**Note** I have go 1.15 on my machine and the tests work just fine, 
must be a Github thing?

## Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by marclop** [comment]
Actually, I think it might be the case where the models were updated to `MS-46` but production is not fully on that version so the `Version` (previously int, now string) returns: 
```
json: cannot unmarshal number into Go value of type spec.SwaggerProps
```

I don't see how it has anything to do with the Go version?

**Comment by karencfv** [comment]
The tests aren't validating against `master` but `1.0` https://github.com/elastic/cloud-sdk-go/blob/master/build/Makefile.apivalidation#L1-L6 . I've ran the tests locally and they past just fine. Between the code that I ported over from the internal repo and what is here, the only difference is the Go version so I figured I'd give that a try 😞

**Comment by karencfv** [comment]
Looking at the output
```
[5:20:30 AM] › [CLI] …  awaiting  Starting Prism…
[5:20:32 AM] › [CLI] ✖  fatal     Unsupported document format
```
This means that it wasn't even able to pull the json... :/ 

And as I can't really replicate this locally, figured since this is the only difference might as well give it a try

**Review by marclop — APPROVED** [review]
Alright! Let's give it a try

**Comment by karencfv** [comment]
Yeah, I'm not super optimistic either, but given that it's an exact copy/paste from the internal repo and I can't replicate the bug, I'm running out of options 😄 

The original workflow was on go 1.13, here I'm setting it to go1.14 and if it doesn't work I'll try setting it to go1.13 again and give it a go.

**Pull request merged**
