### PR TITLE
snaprepoapi: Add PathStyleAccess field to S3Config

### PR DESCRIPTION
**Pull request by pascal-hofmann**
## Description
Add the missing `PathStyleAccess` field to the struct `S3Config` which is used for configuring S3 snapshot repositories. 
See also https://www.elastic.co/guide/en/elasticsearch/reference/current/repository-s3.html#repository-s3-client

Also updates the outdated link to the Elasticsearch official documentation.

## Related Issues
#425

## Motivation and Context
This allows creating S3 snapshot repositories that talk to S3 backends which require path style access.

## How Has This Been Tested?
Ran unit tests and tested against the ECE API.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improves code quality but has no user-facing effect)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Readiness Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

Note: I have issues with make format and make lint. I think this happens because bin/golangci-lint is very old.
> WARN [runner] Can't run linter goanalysis_metalinter: S1031: failed prerequisites: [(inspect@github.com/elastic/cloud-sdk-go/pkg/multierror, isgenerated@github.com/elastic/cloud-sdk-go/pkg/multierror): analysis skipped: errors in package: [/Users/pascal/gec/cloud-sdk-go/pkg/multierror/format.go:21:2: could not import bytes (/usr/local/Cellar/go/1.20.2/libexec/src/bytes/buffer.go:10:2: could not import errors (/usr/local/Cellar/go/1.20.2/libexec/src/errors/wrap.go:8:2: could not import internal/reflectlite (/usr/local/Cellar/go/1.20.2/libexec/src/internal/reflectlite/swapper.go:8:2: could not import internal/goarch (-: could not load export data: cannot import "internal/goarch" (unknown bexport format version -1 …

### CODE REVIEW

**Comment by pascal-hofmann** [comment]
I just verified that this is working via a modified version of terraform-provider-ec that talks to our internal ECE instance.

@tobio, @gigerdo: Can you have a look at this? Would be great to get this merged quickly.

**Review by gigerdo — APPROVED** [review]
Thanks for opening the PR

LGTM :+1:

**Comment by gigerdo** [comment]
To merge you need to sign your commits (https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

**Comment by pascal-hofmann** [comment]
> To merge you need to sign your commits (https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

This is fixed now.

**Pull request merged**
